import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div style={{ margin: "100px auto", padding: 100}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        App
        <hr />
        <ul>
          <li>
            <Link href="/testDynamic">测试Dynamic加载</Link>
          </li>
          <li>
            <Link href="/testImport">测试Import加载</Link>
          </li>
          <li>
            <Link href="/testSlug">测试动态路由(严格模式)，/testSlug，页面报404错误</Link>
          </li>
          <li>
            <Link href="/testSlug/1">测试动态路由(严格模式)， /testSlug/1</Link>
          </li>
          <li>
            <Link href="/testSlug/a/1">测试动态路由(严格模式)，/testSlug/a/1</Link>
          </li>
          <hr />
          <li>
            <Link href="/testSlug2">测试动态路由(严格模式)，/testSlug2，页面不会报404错误</Link>
          </li>
          <li>
            <Link href="/testSlug2/1">测试动态路由(非严格模式)，/testSlug2/1</Link>
          </li>
          <li>
            <Link href="/testSlug2/2">测试动态路由(非严格模式)，/testSlug2/2</Link>
          </li>
          <li>
            <Link href="/testSlug2/3">测试动态路由(非严格模式)，/testSlug2/3</Link>
          </li>
          <li>
            <Link href="/testSlug2/a/1">测试动态路由(非严格模式)，/testSlug/a/1</Link>
          </li>
          <hr />
          <li>
            <Link href="/testPassHref">测试PassHref testPassHref</Link>
          </li>
          <li>
            <Link href="/testFont">testFont</Link>
          </li>
          <li>
            <Link href="/testComponentServer">测试组件的服务端渲染</Link>
          </li>
          <li>
            <Link href="/testI18n" locale="cn">测试i18n--中文</Link>
            <br />
            <Link href="/testI18n" locale="en">测试i18n--英文</Link>
          </li>
        </ul>
      </main>
    </div>
  )
}
